# Generated by Django 4.0.4 on 2022-05-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalskill',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название способности'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название способности'),
        ),
    ]
