# Generated by Django 4.0.4 on 2022-05-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_historicalskill_category_alter_skill_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalthing',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Предмет', 'verbose_name_plural': 'historical Предметы'},
        ),
        migrations.AlterModelOptions(
            name='thing',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
    ]
